### ISSUE TITLE
Mistral 7B

### ISSUE THREAD

**Issue by LakoMoor** [AkariAsai/self-rag#1]
Will there be a release of the Mistral 7b model?

**Comment by AkariAsai** [comment]
We haven't tried the Mistral 7b in our paper but you can easily train it using [our script ](https://github.com/AkariAsai/self-rag/blob/main/retrieval_lm/script_finetune_7b.sh)by replacing the model path with `mistralai/Mistral-7B-v0.1`, after downloading the data at [selfrag/selfrag_train_data](https://huggingface.co/datasets/selfrag/selfrag_train_data). 
Currently, we have limited bandwidth, but we will announce it if we train the 7B model based on Mistral 7b in the next few weeks!
