### ISSUE TITLE
Use Self-RAG with vector databases

### ISSUE THREAD

**Issue by casper-hansen** [AkariAsai/self-rag#10]
The ability to retrieve from a vector database is often how RAG is used in applications. Could you please look into adding langchain or llamaindex support on top to leverage e.g. a Pinecone, Milvus, or Chroma vector store?

**Comment by emrgnt-cmplxty** [comment]
I am preparing an out of the box solution if you are interested

**Comment by casper-hansen** [comment]
> I am preparing an out of the box solution if you are interested

Definitely interested!

**Comment by emrgnt-cmplxty** [comment]
Awesome, I just put a [comment here](https://github.com/AkariAsai/self-rag/issues/9#issuecomment-1783191051) about what I am working on regarding this.

Would love to hear your thoughts in that thread

**Comment by AkariAsai** [comment]
Sorry for my late response, I am currently not plannig to integrate vector DB such as Chroma -- I tried once and found the indexing process was quite slow for 30M passage scale as in the entire English Wikipedia but I might have tried some techniques to enhance the efficiency. The solution by @emrgnt-cmplxty looks really nice, and recommend to check it out!
