### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by merlinarer** [AkariAsai/self-rag#16]
Is this a oversight or ?
https://github.com/AkariAsai/self-rag/blob/b7285a473a5d73f40a28675afac81f874f857b18/retrieval_lm/run_long_form_static.py#L177-L178

**Comment by AkariAsai** [comment]
Could you please provide more details or explain your question further?

**Comment by AkariAsai** [comment]
Oh I think it's a typo when  I was refactoring the code base. Let me quickly fix it.

**Comment by AkariAsai** [comment]
Fixed. Thanks again for reporting the issue. I'm closing it now.

**Comment by AllenShow** [comment]
in run_short_form.py

```
 if len(results) == 1:
        postprocessed_pred = postprocess_answer_option_conditioned(pred)
        return postprocessed_pred, results, do_retrieve
```

> Traceback (most recent call last):
  File "run_short_form.py", line 371, in <module>
    main()
  File "run_short_form.py", line 329, in main
    pred, results, do_retrieve = generate(
  File "run_short_form.py", line 313, in generate
    return call_model_rerank_w_scores_batch(prompt, evidences=evidences, model=model, max_new_tokens=max_new_tokens,
  File "run_short_form.py", line 179, in call_model_rerank_w_scores_batch
    postprocessed_pred = postprocess_answer_option_conditioned(pred)
UnboundLocalError: local variable 'pred' referenced before assignment

How to fix it?
