### ISSUE TITLE
Requirement Confilicts

### ISSUE THREAD

**Issue by zlwang-cs** [AkariAsai/self-rag#26]
Hi,

Thanks for the great work! I am trying to install the requirements at you showed in the repo. However, I encountered the following error: `factscore 0.1.5 depends on openai<0.28.0 and >=0.27.7`.

I understand it could be difficult to maintain the compatible environment given that the dependencies are updating so quickly. It would be great if you can specify a bit in the requirement.txt to make the installation more smoothly.

Thanks!

**Comment by zlwang-cs** [comment]
Some follow ups: it seems that many dependencies are updated after the release of the repo. I am thinking maybe it is helpful to denote the specific verison of the packages used in the project.

**Comment by fate-ubw** [comment]
yes I met the same problem when I install the lib. If you can specify the version of all package, this problem will be fixed.

**Comment by AkariAsai** [comment]
Hi, thank you so much for reporting, and your suggetions! 
Would you be able to list the versions you are using? @zlwang-cs @fate-ubw 
I will update the README accordingly! 
I updated the conda environment I was using for this project recently, so some packaeges may not be the same as the original code base...

**Comment by zlwang-cs** [comment]
@AkariAsai Hi, I list the package versions in the pull request. Let me know if the environment works. Feel free to update it to improve the compatibility.

**Comment by AkariAsai** [comment]
I merged the PR. Thank you so much!!
