### ISSUE TITLE
requirement confilicts for vllm and fast-attn

### ISSUE THREAD

**Issue by xhd0728** [AkariAsai/self-rag#27]
Hi, I encountered some issues while trying to run it. I attempted to install the dependency package in `requirements.txt`, but found a version conflict between two packages:

```
fast-attn requires torch>=1.13.0 and torch<2.0.0
vllm requires torch>=2.0.0.
```

besides, I also encountered a problem same to #26,
may I ask if you have encountered this problem? thank you!

**Comment by Loose-Gu** [comment]
You can only install torch and vllm for inference, factscore is for evaluation of Bio. Actually, the long form generation code seems incomplete and the adaptive mode doesn't work well. So you can skip factscore installation if you just want to make it run.

**Comment by xhd0728** [comment]
thanks, I will give it a shot🤗

**Comment by AkariAsai** [comment]
Hi @xhd0728 sorry for my late response! As @Loose-Gu mentions, you can create a separate env for `factscore` if the issue remains. I also had a similar issue when I was working on the project, so I ended up creating a separate environment. I'll update the readme and requirements.txt shortly. Thanks for your patience!

**Comment by AkariAsai** [comment]
FYI: A new PR is merged to fix the conflicts (Thanks @zlwang-cs!). Please git pull again if you still see the issue. 
[#32](https://github.com/AkariAsai/self-rag/pull/32)
