### ISSUE TITLE
How to open dir enwiki_dec_2020_contriever_intro/ ？

### ISSUE THREAD

**Issue by YuqiNWang** [AkariAsai/self-rag#29]
IDE shows file passage_0X is not uft-8. I have tried macOS roman, DOS..., but not work.  Please tell me which encoding is correct one?

**Comment by YuqiNWang** [comment]
I find line 178 in self-rag/retrieval_lm/passage_retrieval.py. Are they embedding of enwiki_2020_dec_intro_only.jsonl?

**Comment by AkariAsai** [comment]
passages are the passage files while embedings are the `passage_*` files. Would you be able to copy and paste the error message from your IDE? I can take a look!

**Comment by AkariAsai** [comment]
I'm closing this issue now but feel free to reopen it!
