### ISSUE TITLE
chatgpt_usefulness.py

### ISSUE THREAD

**Issue by akesh1235** [AkariAsai/self-rag#3]
I cannot find this chatgpt _usefulness.py file to generate data.

**Comment by AkariAsai** [comment]
The file name should be [chatgpt_utility.py](https://github.com/AkariAsai/self-rag/blob/main/data_creation/critic/gpt4_reward/chatgpt_utility.py)! I'll fix README files accordingly.

**Comment by AkariAsai** [comment]
Closing this issue now.
