### ISSUE TITLE
If it's possible to use LoRA to train critic and generator

### ISSUE THREAD

**Issue by phoenixqaq** [AkariAsai/self-rag#33]
Hi there @AkariAsai , I'm a beginner and wondering if it is possible to use **LoRA** to train the critic and generator? Because i have a try to train the generator and it needs 200+ hours(i only have 2*a100 40g)
If it's possible, i'm also wondering how to expand token vocabularies with reflection tokens

Thank you very much!

**Comment by phoenixqaq** [comment]
If there is a need to use sentence-piece?

**Comment by AkariAsai** [comment]
Once training corpus is augmented, Self-RAG training is similar to standard fine-tuning so it should be fine. On the other hand, many LORA fine-tuning codes often don't support embedding layer updates for the new special tokens. 
I remember when I was trying to use lora or qlora, `peft` back then didn't fully support embedding layer updates, as discussed in this open issue [here](https://github.com/huggingface/peft/issues/334). 
You might need to try some tricks to update embedding layers during LORA fine-tuning.

**Comment by ncsulsj** [comment]
The peft lora now supports the embedding layer by adding "embed_tokens" in the target modules.

**Comment by roynirmal** [comment]
How do we load the model if we have fine-tuned using lora? i think vllm does not support loading lora checkpoints. Any pointers? @ncsulsj @AkariAsai

**Comment by AkariAsai** [comment]
Hmm, I've never tried by myself so am not sure... I can ask around!

**Comment by AkariAsai** [comment]
Some people explore the way to download LORA models and run inference using vllm. [vllm/issues/3404](https://github.com/vllm-project/vllm/issues/3404). 
Probably the main vllm repository can provide a better support for this issue, so I recommend opening issues there!
