### ISSUE TITLE
About bio eval

### ISSUE THREAD

**Issue by aJupyter** [AkariAsai/self-rag#87]
Great job.
Regarding the bio data eval work, I didn't find the parameter you described in the FActScore repository - data_path YOUR_OUTPUT_FILE - am I missing something?
Looking forward to your reply!

![image](https://github.com/user-attachments/assets/81434721-c0b2-4b16-99da-0dd8b9de3177)
![image](https://github.com/user-attachments/assets/73141cef-4bdb-4faf-b213-c103418aa103)

**Comment by fate-ubw** [comment]
I also spent a considerable amount of time on this section, as the README for selfrag did not provide detailed instructions on how to use factscore. It took me some time to figure out the correct configuration. You can refer to the library I developed: [RAGLAB](https://github.com/fate-ubw/RAGLAB/tree/main), where I have refactored the selfrag algorithm and evaluation process, offering clearer and more concise code. I recommend using the script I've configured to address this issue: https://github.com/fate-ubw/RAGLAB/blob/main/run/Factscore/2-eval_fact-raglab-selfrag-selfrag_8B-always_retrieval-GPT.sh
